# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43292203bdaf7d27a3ebb1d8bc64e1c6649b9b146e6f5066ed14b6df5e04470375e6c568c4d952932f243f74dc4d2ef2c80cedd6cfb079abb7624dbbce5929dc

test:
  secret_key_base: 620b208a39cc622418d26d8e8249b0d10f054095179fc1608e07ae87ad5f45a4d7be52f0686ae97bae5f275488eab09e8a433697c86fd9199c2a8fe3c4931f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
